"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.version = void 0;
// Generated by genversion.
const version = '12.8.0';
exports.version = version;
//# sourceMappingURL=version.js.map